"use client";

import { Download, FileText } from "lucide-react";
import { Kpi } from "@/components/kpi";
import { BatchSelectionGate } from "@/components/shell";
import { EmptyState } from "@/components/status";
import { ViewScopeBanner, ViewScopeSelect } from "@/components/view-scope-select";
import { reportUrl } from "@/lib/api";
import { isCumulativeView, useDataView } from "@/lib/data-view";

const REPORTS = [
  {
    kind: "high-risk",
    label: "High-risk anomaly report",
    group: "Data & quality",
    description: "Records requiring attention based on persisted high-risk anomaly evidence.",
  },
  {
    kind: "anomalies",
    label: "Full anomaly report",
    group: "Data & quality",
    description: "Confirmed anomaly evidence available for the current survey batch.",
  },
  {
    kind: "enumerators",
    label: "Enumerator report",
    group: "Data & quality",
    description: "Enumerator-level workload and quality signals.",
  },
  {
    kind: "districts",
    label: "District report",
    group: "Data & quality",
    description: "District-level quality and risk comparison data.",
  },
  {
    kind: "batch",
    label: "Batch validation report",
    group: "Data & quality",
    description: "Validation results associated with the selected survey batch.",
  },
  {
    kind: "investigations",
    label: "Investigation report",
    group: "Investigation",
    description: "Investigation records and supervisor workflow evidence.",
  },
] as const;

const GROUPS = ["Data & quality", "Investigation"] as const;

export default function ReportsPage() {
  const [view, setView] = useDataView();
  return (
    <BatchSelectionGate emptyDetail="Select a batch before exporting reports.">
      {(batchId) => <ReportsInner batchId={batchId} view={view} onViewChange={setView} />}
    </BatchSelectionGate>
  );
}

function ReportsInner({
  batchId,
  view,
  onViewChange,
}: {
  batchId: string;
  view: ReturnType<typeof useDataView>[0];
  onViewChange: ReturnType<typeof useDataView>[1];
}) {
  const cumulative = isCumulativeView(view);
  return (
    <div className="space-y-6">
      <div>
        <p className="sv-label">Reports</p>
        <h1 className="mt-1 text-2xl font-semibold text-inst-navy">Reports & exports</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-inst-text-secondary">
          Download validated reports generated from persisted survey evidence.
        </p>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-inst-text-secondary">
          Risk scores and classifications are generated by the backend. The browser does not recompute risk.
        </p>
        <div className="mt-4">
          <ViewScopeSelect view={view} onChange={onViewChange} />
        </div>
        <ViewScopeBanner view={view} batchId={batchId} />
      </div>

      <div className="rounded border border-inst-border bg-inst-muted px-4 py-3 text-sm leading-6 text-inst-text-secondary">
        {cumulative
          ? "Cumulative Records — All Batches. Downloads are generated from persisted evidence across every processed batch."
          : "Generated from persisted backend evidence. The browser does not recompute risk."}
      </div>

      <div className="max-w-xs">
        <Kpi
          label="Available reports"
          value={REPORTS.length}
          available
          hint={cumulative ? "Export types for all processed batches" : "Export types for the selected batch"}
          icon={FileText}
          tone="info"
        />
      </div>

      {!REPORTS.length ? (
        <EmptyState
          title="No reports available"
          detail="Generated reports will appear here once evidence has been persisted."
        />
      ) : (
        GROUPS.map((group) => {
          const items = REPORTS.filter((item) => item.group === group);
          if (!items.length) return null;
          return (
            <section key={group} className="sv-card overflow-hidden">
              <div className="border-b border-inst-border bg-inst-muted px-4 py-3">
                <h2 className="text-sm font-semibold uppercase tracking-wide text-inst-navy">{group}</h2>
              </div>
              <ul>
                {items.map((item) => (
                  <li
                    key={item.kind}
                    className="flex flex-wrap items-start justify-between gap-4 border-b border-inst-border px-4 py-4 last:border-b-0"
                  >
                    <div className="flex min-w-0 flex-1 gap-3">
                      <span className="sv-metric-icon bg-[#e8eef5] text-inst-blue" aria-hidden="true">
                        <FileText className="h-4 w-4" />
                      </span>
                      <div className="min-w-0">
                        <p className="text-sm font-semibold text-inst-navy">{item.label}</p>
                        <p className="mt-1 text-sm leading-6 text-inst-text-secondary">
                          {cumulative && item.kind === "batch"
                            ? "Validation results associated with all processed batches."
                            : cumulative && item.kind === "anomalies"
                              ? "Confirmed anomaly evidence across all processed batches."
                              : item.description}
                        </p>
                      </div>
                    </div>
                    <a
                      className="sv-btn-compact shrink-0"
                      href={reportUrl(item.kind, batchId, view)}
                      aria-label={`Download ${item.label} as CSV`}
                    >
                      <Download className="h-4 w-4" aria-hidden="true" />
                      Download CSV
                    </a>
                  </li>
                ))}
              </ul>
            </section>
          );
        })
      )}
    </div>
  );
}
